# Generated by Django 4.0.4 on 2022-10-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
        ('blog', '0002_alter_blogcomment_post_alter_blogcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.profile'),
        ),
    ]
