"""
Django settings for cms project.

Generated by 'django-admin startproject' using Django 3.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# import django_heroku
import os
import sys
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'blog',
    'django.contrib.humanize',
    'django_celery_beat',  # For periodic task scheduling
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(os.path.dirname(__file__), "static"),
)

STATICFILES_STORAGE =  'django.contrib.staticfiles.storage.StaticFilesStorage' 

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR / "static"),
# ]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


LOGIN_REDIRECT_URL = '/blogs'

LOGOUT_REDIRECT_URL = '/blogs'



# AUTH_USER_MODEL = 'account.User'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

#tinymce configuration
TINYMCE_JS_URL = os.path.join(MEDIA_URL, "tinymce/js/tinymce/tinymce.min.js")
TINYMCE_JS_ROOT = os.path.join(MEDIA_ROOT, "tinymce")

TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'selector': 'textarea',
    # 'menubar':'edit',
    'toolbar': 'image',
    'plugins': "table,spellchecker,paste,searchreplace,image imagetools",
    'imagetools_toolbar': 'rotateleft rotateright | flipv fliph | editimage imageoptions',
    'paste_data_images': True
}

# Cache configuration
# For development: Using local memory cache (no Redis required)
# For production: Uncomment Redis configuration below
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # Default timeout in seconds (5 minutes)
    }
}

# Redis configuration (uncomment when Redis is running)
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'cms_cache',
#         'TIMEOUT': 300,
#     }
# }

# Session backend - using database instead of cache for development
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# For Redis sessions (uncomment when Redis is running):
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_CACHE_ALIAS = 'default'

# Email Configuration
# ============================================================================
# GMAIL SETUP INSTRUCTIONS (if getting "Application-specific password required"):
# ============================================================================
# 
# STEP 1: Enable 2-Step Verification
#   → Go to: https://myaccount.google.com/security
#   → Click "2-Step Verification" and enable it (if not already enabled)
#   → You MUST complete this step before app passwords will work!
#
# STEP 2: Generate App-Specific Password
#   → Go to: https://myaccount.google.com/apppasswords
#   → Select "Mail" from the first dropdown
#   → Select "Other (Custom name)" from the second dropdown
#   → Enter: "Django CMS" as the name
#   → Click "Generate"
#   → Copy the 16-character password (it will show as "abcd efgh ijkl mnop")
#
# STEP 3: Remove ALL Spaces
#   → The password Gmail shows: "vrlt jdim rrvr qdjd"
#   → Use in settings (NO SPACES): "vrltjdimrrvrqdjd"
#   → App passwords are exactly 16 characters WITHOUT spaces
#
# STEP 4: Update settings.py
#   → Replace EMAIL_HOST_PASSWORD below with your new password (no spaces)
#   → Restart Celery worker after updating
#
# STEP 5: Test the configuration
#   → Run: python manage.py shell < test_email.py
#   → Or use Django shell to test email sending
#
# TROUBLESHOOTING:
#   - If still getting errors, try generating a NEW app password
#   - Make sure 2-Step Verification is actually enabled (not just set up)
#   - Verify you're using the correct Gmail account
#   - Check that the password has exactly 16 characters (no spaces)
# ============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# IMPORTANT: App-specific password must be 16 characters WITHOUT spaces
# Current password: vrltjdimrrvrqdjd (16 chars, no spaces - format is correct)
# If still getting errors, generate a NEW app password and replace this value
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# Celery Configuration
# Note: Redis must be running for Celery to work
# To install Redis on Windows:
#   1. Use Docker: docker run -d -p 6379:6379 redis
#   2. Or use WSL: wsl -> sudo apt-get install redis-server -> redis-server
#   3. Or download from: https://github.com/microsoftarchive/redis/releases
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # Redis as message broker
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'  # Redis as result backend
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Connection and retry settings
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Retry connection on startup
CELERY_BROKER_CONNECTION_RETRY = True  # Enable connection retries
CELERY_BROKER_CONNECTION_MAX_RETRIES = 100  # Maximum retry attempts

# Task acknowledgment settings (for connection loss handling)
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion
CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS = False  # Don't cancel tasks on connection loss (Celery 5.1 default)

# If Redis is not available, tasks will fail gracefully (handled in views)
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for testing without Redis (tasks run synchronously)

# Celery Beat Configuration (for periodic tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Windows-specific configuration
# Use 'solo' pool on Windows to avoid multiprocessing permission issues
# The 'solo' pool runs tasks in the same process (no multiprocessing)
# For production on Linux/Unix, use 'prefork' or 'gevent' pools
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'  # Use solo pool on Windows
    # Alternative: Use threads pool (uncomment if you need concurrency)
    # CELERY_WORKER_POOL = 'threads'
    # CELERY_WORKER_CONCURRENCY = 4

# django_heroku.settings(locals())